version: '3'
services:
  frontend:
    image: harsh788/frontend_image
    container_name: frontend_container
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: harsh788/backend_image
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - /home/harsh/Acads/sem7/SPE/SAC_Election_Portal/data:/data/db:rw

